#!/usr/bin/env python3
"""
Plot small-multiple mechanism-share charts from mechanism_label_differences.csv.

Input is generated by:
    scripts/llm_judge/build_justification_report.py

Main input:
    mechanism_label_differences.csv

Outputs:
1) mechanism_shares.png
"""

from __future__ import annotations

import argparse
import math
import textwrap
from pathlib import Path

import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import numpy as np
import pandas as pd

from coopeval.llm_judge.plotting_utils import (
    mechanism_differences_csv_path,
    prepare_figure_subdir,
    validate_input_name,
)
from coopeval.script_utils.display_helper import (
    format_mechanism_name,
    sort_mechanisms,
)
from coopeval.script_utils.figure_exports import save_matplotlib_figure


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments for the mechanism share small multiples."""
    parser = argparse.ArgumentParser(
        description=(
            "Create mechanism-share small multiples from "
            "mechanism_label_differences.csv."
        )
    )
    parser.add_argument(
        "input_name",
        type=str,
        help=(
            "Judge run identifier (auto-discovers mechanism_label_differences.csv)."
        ),
    )
    parser.add_argument(
        "--output-stem",
        type=str,
        default="mechanism_shares",
        help="Output filename stem (default: mechanism_shares).",
    )
    parser.add_argument(
        "--ncols",
        type=int,
        default=4,
        help="Number of subplot columns (default: 4).",
    )
    parser.add_argument(
        "--max-labels",
        type=int,
        default=None,
        help="Optional max number of label rows to plot.",
    )
    parser.add_argument(
        "--dpi",
        type=int,
        default=300,
        help="Figure DPI (default: 300).",
    )
    args = parser.parse_args()
    args.input_name = validate_input_name(args.input_name)
    return args


def sig_marker(p_value: float) -> str:
    """Return a string marker describing statistical significance."""
    if p_value < 0.001:
        return "***"
    if p_value < 0.01:
        return "**"
    if p_value < 0.05:
        return "*"
    return "n.s."


def load_and_prepare(
    path: Path, max_labels: int | None
) -> tuple[pd.DataFrame, list[str]]:
    """Load the CSV and return a filtered dataframe plus share columns."""
    df = pd.read_csv(path)
    required = {"label", "cramers_v"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(
            f"Missing required columns in {path}: {sorted(missing)}"
        )

    share_cols = [c for c in df.columns if c.startswith("share_pct__")]
    if not share_cols:
        raise ValueError(
            "No share columns found. Expected columns like share_pct__Contracting."
        )

    for col in share_cols + ["cramers_v"]:
        df[col] = pd.to_numeric(df[col], errors="coerce")
    if "p_bh" in df.columns:
        df["p_bh"] = pd.to_numeric(df["p_bh"], errors="coerce")
    elif "p_value" in df.columns:
        df["p_bh"] = pd.to_numeric(df["p_value"], errors="coerce")
    else:
        df["p_bh"] = np.nan

    df = df.sort_values("cramers_v", ascending=False).reset_index(drop=True)
    if max_labels is not None and max_labels > 0:
        df = df.head(max_labels).copy()

    return df, share_cols


def plot_small_multiples(
    df: pd.DataFrame,
    share_cols: list[str],
    output_prefix: Path,
    ncols: int,
    dpi: int,
) -> None:
    """Render the multi-panel mechanism share chart and save it."""
    n = len(df)
    if n == 0:
        raise ValueError("No rows available to plot.")
    ncols = max(1, ncols)
    nrows = math.ceil(n / ncols)

    line_color = "#2E5FA3"
    dot_color = "#2E5FA3"
    area_color = "#D0DFF5"

    fig_w = max(10.5, 3.3 * ncols)
    fig_h = max(7.0, 2.8 * nrows)
    fig, axes = plt.subplots(nrows, ncols, figsize=(fig_w, fig_h))
    axes_flat = np.array(axes).reshape(-1)

    for i, (_, row) in enumerate(df.iterrows()):
        ax = axes_flat[i]

        vals: dict[str, float] = {}
        for col in share_cols:
            mech_key = col.split("share_pct__", 1)[1]
            vals[format_mechanism_name(mech_key)] = float(row[col])

        sorted_mech_keys = sort_mechanisms(vals)
        x_labels = [format_mechanism_name(k) for k in sorted_mech_keys]
        y_vals = [vals[k] for k in sorted_mech_keys]
        x_pos = np.arange(len(x_labels))

        ax.fill_between(x_pos, y_vals, alpha=0.15, color=area_color, zorder=1)
        ax.plot(x_pos, y_vals, color=line_color, linewidth=1.6, zorder=2)
        ax.scatter(
            x_pos, y_vals, color=dot_color, s=28, zorder=3, clip_on=False
        )

        ax.set_xticks(x_pos)
        ax.set_xticklabels(
            x_labels,
            fontsize=5.7,
            rotation=40,
            ha="right",
            rotation_mode="anchor",
        )

        marker = (
            sig_marker(float(row["p_bh"])) if pd.notna(row["p_bh"]) else "n/a"
        )
        raw_title = str(row["label"])
        wrapped_title = "\n".join(textwrap.wrap(raw_title, width=28))
        ax.set_title(
            f"{wrapped_title}\n$V={float(row['cramers_v']):.3f}${marker}",
            fontsize=7.0,
            fontweight="bold",
            pad=4,
            loc="left",
        )

        ax.yaxis.set_major_formatter(mticker.FormatStrFormatter("%.0f%%"))
        ax.tick_params(axis="y", labelsize=6)
        ax.set_xlim(-0.4, len(x_labels) - 0.6)
        ymax = max(y_vals) * 1.18 if max(y_vals) > 0 else 1.0
        ax.set_ylim(0, ymax)

        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.spines["left"].set_linewidth(0.6)
        ax.spines["bottom"].set_linewidth(0.6)
        ax.tick_params(axis="both", which="both", length=2)
        ax.yaxis.set_tick_params(width=0.6)

    for j in range(n, len(axes_flat)):
        axes_flat[j].set_visible(False)

    fig.suptitle(
        "Share of reasoning label by enforcement mechanism\n"
        "(subplots ordered by Cramer's V)",
        fontsize=9,
        y=1.01,
        x=0.02,
        ha="left",
        fontweight="bold",
    )

    plt.tight_layout(h_pad=3.2, w_pad=2.0)
    saved_paths = save_matplotlib_figure(
        fig,
        output_prefix,
        ("png",),
        dpi=dpi,
        root_dir=output_prefix.parent,
        bbox_inches="tight",
    )
    plt.close(fig)
    for path in saved_paths:
        print(f"Wrote: {path}")


def main() -> None:
    """CLI entry point for plotting mechanism share differences."""
    args = parse_args()
    input_name = args.input_name
    csv_path = mechanism_differences_csv_path(input_name)
    df, share_cols = load_and_prepare(csv_path, args.max_labels)
    plot_root = prepare_figure_subdir(
        input_name, "taxonomy_mechanism_differences"
    )
    output_prefix = plot_root / args.output_stem
    plot_small_multiples(
        df=df,
        share_cols=share_cols,
        output_prefix=output_prefix,
        ncols=args.ncols,
        dpi=args.dpi,
    )


if __name__ == "__main__":
    main()
